add_newline = true

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$jobs\
$shell
$status$character"""

[username]
format = '[$user]($style) @ '

[hostname]
ssh_only = true
ssh_symbol = ''

[git_status]
untracked = ''

[directory]
truncation_length = 4
truncation_symbol = '…/'

[status]
disabled = false
symbol = ''

[jobs]
format = '[\[$symbol$number\]]($style) '
symbol = '&'
style = 'yellow'

[python]
format = '[${symbol}(\($virtualenv\) )]($style)'
symbol = ''
