#! /bin/sh

trap 'jobs -p | xargs kill' EXIT

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc config window_gap          12

bspc config border_width         2
bspc config focused_border_color "#3B4252"
bspc config normal_border_color  "#282e3a"

#bspc config split_ratio          0.52

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       false

pgrep -x sxhkd > /dev/null || sxhkd &
~/scripts/polybar.sh &
~/scripts/autostart.sh bspwm &

wait

#
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating focus=on
