#!/usr/bin/env bash

rofi_choice () {
  echo -e "Lock\nSuspend\nLogout\nReboot\nShutdown" | \
    rofi -show drun -show-icons -width 20 -l 5 -dmenu -i
}


choice=$(rofi_choice)

case $choice in
  Lock)
    "$HOME/scripts/lock.sh"
    ;;

  Suspend)
    systemctl suspend
    ;;

  Logout)
    bspc quit
    ;;

  Reboot)
    systemctl reboot
    ;;

  Shutdown)
    systemctl poweroff
    ;;
esac
